### ISSUE TITLE
build.sh combines findlib and non-findlib compliant libraries unnecessarily

### ISSUE THREAD

**Issue by carlos-molina** [yansh/MoanaML#13]
Yan
the original build.sh uses -package and -libs. If my interpretation of the ocamlbuild man is correct, the script unnecessarily combines libraries that are findlib compliant (those called by -package) with others that are non-findlib compliant (those called by -libs). 

#!/bin/bash
eval `opam config env`

ocamlbuild -r -use-ocamlfind -use-menhir -classic-display -package yojson,atdgen,irmin,irmin.backend,irmin.unix -libs unix,lwt-unix,git-unix,irmin,irmin-server,irmin-unix -tag thread  tests.byte contacts.byte

./tests.byte
./contacts.byte

You can compile and get the same execution results with -package only. See the alternative build.sh

#!/bin/bash
eval `opam config env`

ocamlbuild -r -use-ocamlfind -use-menhir -classic-display -package lwt,yojson,atdgen,irmin,irmin.backend,irmin.server,git.unix,irmin.unix -tag thread  tests.byte contacts.byte

./tests.byte
./contacts.byte

**Comment by yansh** [comment]
Thanks @carlos-molina, can you create a seperate PL for it. Let's see if TRAVIS complains.
