### ISSUE TITLE
Port the code to support the new Irmin version

### ISSUE THREAD

**Issue by yansh** [yansh/MoanaML#15]
New Irmin (0.9.X) include some changes to the API. Some of the code needs to be refactored to support it.

**Comment by samoht** [comment]
I'm happy to help with that one if you are stuck with some changes

**Comment by yansh** [comment]
Awesome, thanks! I am working on it right now. I'll you know how it goes.

**Comment by yansh** [comment]
@samoht I am struggling with moana_irmin.ml. What is the alternative API for setting up a Store and consequently the View. 
```
module Git =
  IrminGit.FS(struct let root = Some "/tmp/irmin/moana"

                        let bare = true
                           end)
  
(* Values are Strings * *)
module Store = Git.Make(IrminKey.SHA1)(IrminContents.String)(IrminTag.String)

```
I am trying to put something together the examples, maybe you can take peek.

**Comment by samoht** [comment]
I've simplified the `view` API a little bit more in master. Will do a release shortly the changes....

about the doc: yes please! any help on that side would be gladly appreciated!
