### ISSUE TITLE
current version of to_json can't handle subj= Variable "?x"

### ISSUE THREAD

**Issue by carlos-molina** [yansh/MoanaML#16]
The tuple type includes the constructor Variable which is not acceptable by the current version of Helper.to_json, it can handle Constant but not Variable.

What's the plan to achieve compatibility?. I'm thinking in enhancing to_json

Carlos

**Comment by yansh** [comment]
Thanks. This was done somewhat intentionally, because to_json meant to be used for converting tuples (not tuple queries) to json format for storage.

**Comment by yansh** [comment]
Implemented a new set of functions that cover this in 18451a6392e9cd1d086e910494e6a5acd823ade8
